New generators
SwissCorePy/pyTelegramBotCAPTCHA pull request #23
Opened 2022-01-08 22:24 UTC by TheAwiteb

# add two new generators 🔥
math and multicolor use [multicolorcaptcha](https://github.com/J-Rios/multicolorcaptcha) library

## multicolor
![Example2](https://i.suar.me/P2PVd/s)

## math
![Example2](https://i.suar.me/vXY00/s)

2022-01-09 07:34 UTC, coder2020official requested changes
What about renaming math generator to numeric?
And, another suggestion: Instead of passing string to captcha options to choose generator, it would be better to create an enum class with all generator names in there.

```
class Generators(str, enum.Enum):
    default: str='default'
    numeric: str='numeric'
    # and so on...

and pass Generators.name to value for generator

```

2022-01-09 07:39 UTC, coder2020official commented
Also, just to remind that black style is beta product, we need more testing
https://github.com/psf/black#note-this-is-a-beta-product

2022-01-09 08:31 UTC, TheAwiteb commented
> What about renaming math generator to numeric? And, another suggestion: Instead of passing string to captcha options to choose generator, it would be better to create an enum class with all generator names in there.
> 
> ```
> class Generators(str, enum.Enum):
>     default: str='default'
>     numeric: str='numeric'
>     # and so on...
> 
> and pass Generators.name to value for generator
> ```

math generator generates mathematical captcha not numeric why rename it to numeric

2022-01-09 08:39 UTC, coder2020official commented
Okay, let it stay math

2022-01-09 12:48 UTC, TheAwiteb reviewed
Well I will put the generators in the Enum

2022-01-10 13:37 UTC, SwissCorePy requested changes
Looks good to me. Thank you very much!

I also like the idea of putting the generators in an enum class, maybe called `Generator`.

2022-01-12 17:16 UTC, coder2020official commented
This will lead to breaking change. Generator shoul accept string as well.

2022-01-12 17:18 UTC, coder2020official reviewed
Just put Generator.name in examples. Captcha should not check whether a class variable is passed, it should still check string's generator name.

2022-01-12 17:31 UTC, coder2020official commented
I had to manually edit requirements.txt to resolve conflict. sorry for that.

2022-01-12 18:23 UTC, TheAwiteb commented on pyTelegramBotCaptcha/telebot_captcha.py
> +        self._generator: str = Generator(generator.lower()).name
Hi @coder2020official . I understood from you that the commit to which Enum was added, does not accept strings as generator name, but I did not make any change in the structure of the code. It accepts strings as before, and the function of Enum is only verification as you see here

2022-01-12 18:35 UTC, coder2020official commented
I will test as soon as i have time.
I am not sure on your 'black code style' - there are too many changes involving extra spaces. I think it would be good to return to old style, or review will take time.

2022-01-12 19:20 UTC, TheAwiteb commented
> I will test as soon as i have time. I am not sure on your 'black code style' - there are too many changes involving extra spaces. I think it would be good to return to old style, or review will take time.

The Black Style was in one commit that will make it easier for you to review it, thank you! 🤩

2022-01-13 09:56 UTC, TheAwiteb commented
> What about renaming math generator to numeric? And, another suggestion: Instead of passing string to captcha options to choose generator, it would be better to create an enum class with all generator names in there.
> 
> ```
> class Generators(str, enum.Enum):
>     default: str='default'
>     numeric: str='numeric'
>     # and so on...
> 
> and pass Generators.name to value for generator
> ```

The enum has been added. You can close the request

2022-01-14 04:20 UTC, coder2020official approved these changes

2022-01-14 04:21 UTC, coder2020official commented
I will test generators. I will write feedback as i test them.

2022-01-14 16:41 UTC, SwissCorePy reviewed
Looks great 👍 
But I currently no time to do the tests.

2022-01-14 16:41 UTC, SwissCorePy approved these changes

2022-01-22 11:22 UTC, merged